server:
  port: 8999 #项目端口

spring:
  application:
    name: blog-web
  profiles:
      active: dev
  mvc:
    pathmatch: #Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ANT_PATH_MATCHER
  main:
      allow-bean-definition-overriding: true

dubbo:
  application:
    name: blog-web
  protocol:
    name: dubbo
    port: 20880

emos:
  jwt:
    #密钥
    secret: abc123456
    #令牌过期时间（天）
    expire: 5
    #令牌缓存时间（天数）
    cache-expire: 10



